version: '2'

services:
  server:
    image: seblaporte/rpi-domoticz:release-19.01
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./config:/mqtt/config:ro
      - ./data:/mqtt/data:rw
