version: '2'

services:
  server:
    image: losjetztdirk/rpi-mosquitto-1884:latest
    ports:
      - 1884:1884
      - 8884:8884
    volumes:
      - ./config:/mqtt/config:ro
      - ./data:/mqtt/data:rw
